apiVersion: v1
kind: Config
current-context: dev-context
clusters:
- name: dev-cluster
  cluster:
    server: https://dev-cluster.example.com
    certificate-authority: /path/to/dev-cluster/ca.crt
- name: prod-cluster
  cluster:
    server: https://prod-cluster.example.com
    certificate-authority: /path/to/prod-cluster/ca.crt

users:
- name: dev-user
  user:
    client-certificate: /path/to/dev-user.crt
    client-key: /path/to/dev-user.key
- name: prod-user
  user:
    client-certificate: /path/to/prod-user.crt
    client-key: /path/to/prod-user.key

contexts:
- name: dev-context
  context:
    cluster: dev-cluster
    user: dev-user
- name: prod-context
  context:
    cluster: prod-cluster
    user: prod-user
