apiVersion: v1
kind: LimitRange
metadata:
  name: example-limit-range
  namespace: default
spec:
  limits:
  - type: Pod
    max:
      memory: "2Gi"
      cpu: "2"
    min:
      memory: "64Mi"
      cpu: "250m"
  - type: Container
    max:
      memory: "1Gi"
      cpu: "1"
    min:
      memory: "64Mi"
      cpu: "250m"
    default:
      memory: "512Mi"
      cpu: "500m"
    defaultRequest:
      memory: "256Mi"
      cpu: "200m"