apiVersion: v1
kind: ResourceQuota
metadata:
  name: example-resource-quota
  namespace: default
spec:
  hard:
    requests.cpu: "4"
    requests.memory: "8Gi"
    limits.cpu: "8"
    limits.memory: "16Gi"
    pods: "100"
    services: "10"
    persistentvolumeclaims: "20"
    configmaps: "10"
    secrets: "10"
