apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  password: cGFzc3dvcmQ=  # base64 encoded value of 'password'
  username: dXNlcm5hbWU=  # base64 encoded value of 'username'

# all values should be encoded
# echo -n "password" | base64    // use -n to avoid adding \n to encoded string
# echo -n "cGFzc3dvcmQ=" | base64 --decode